---
title: "Air quality"
format: html
editor: visual
---

# Setup

```{r}
#| label: load-packages
#| message: false

library(tidyverse)

dch_2022 <- read_csv(
  here::here("data/durham-chapel-hill/ad_aqi_tracker_data-2022.csv"),
  na = c(".", "")
) |>
  janitor::clean_names() |>
  mutate(date = mdy(date))

aqi_levels <- tribble(
  ~aqi_min, ~aqi_max, ~color,    ~level,
  0,        50,       "#D8EEDA", "Good",
  51,       100,      "#F1E7D4", "Moderate",
  101,      150,      "#F8E4D8", "Unhealthy for sensitive groups",
  151,      200,      "#FEE2E1", "Unhealthy",
  201,      300,      "#F4E3F7", "Very unhealthy",
  301,      400,      "#F9D0D4", "Hazardous"
)
```

```{r}
#bizarre plot 
ggplot(dch_2022, aes(x = date, y = aqi_value, group = 1)) + geom_line()
```

# Visualizing Durham AQI

```{r}
#| label: label-me-1
#| fig-width: 8
#| fig-asp: 0.4

dch_2022 %>%
  ggplot(aes(x = date, y = aqi_value, group = 1)) +
  geom_line(linewidth = 0.8, show.legend = FALSE)
```

```{r}
#label: recreating visualization

ggplot() + 
  geom_rect(data = aqi_levels, aes(ymin = aqi_min, ymax = aqi_max, fill = color), xmin = -Inf, xmax = Inf,) +
  geom_text(data = aqi_levels, aes(x = as.Date("2023-02-28"), y = (aqi_max + aqi_min)/2, label = level), hjust = "inward", size = 6, color = "white", fontface = "bold") +
  geom_line(data = dch_2022, aes(x = date, y = aqi_value, group = 1), linewidth = 0.8) +
  scale_y_continuous(limits = c(0,400)) +
  scale_fill_identity() +
  scale_x_continuous(breaks = as.Date(c("2022-01-01", "2022-04-01", "2022-07-01", "2022-10-01","2023-01-01", "2023-03-01")), labels = c("Jan\n 2022", "Apr", "Jul", "Oct", "Jan \n2023", "")) + 
  labs(x = "", 
       y = "AQI", 
       title = "Ozone and PM2.5 Daily AQI Values", 
       subtitle = "Durham-Chape Hill, NC", 
       caption = "Source: EPA Daily Air Quality Tracker") +
  theme_minimal()
  
```
